// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Gogli1Test {
    private IWebDriver driver;
    public IDictionary<string, object> vars { get; private set; }
    private IJavaScriptExecutor js;
    [SetUp]
    public void SetUp() {
        driver = new ChromeDriver();
        js = (IJavaScriptExecutor)driver;
        vars = new Dictionary<string, object>();
    }
    [TearDown]
    protected void TearDown() {
        driver.Quit();
    }
    public string waitForWindow(int timeout) {
        try {
            Thread.Sleep(timeout);
        } catch (Exception e) {
            Console.WriteLine("{0} Exception caught.", e);
        }
        var whNow = ((IReadOnlyCollection<object>)driver.WindowHandles).ToList();
        var whThen = ((IReadOnlyCollection<object>)vars["WindowHandles"]).ToList();
        if (whNow.Count > whThen.Count) {
            return whNow.Except(whThen).First().ToString();
        } else {
            return whNow.First().ToString();
        }
    }
    [Test]
    public void gogli1() {
        driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(2);
        driver.Navigate().GoToUrl("https://cloud.google.com/products/calculator");
        driver.Manage().Window.Maximize();
        driver.FindElement(By.XPath("//div[@id=\'ucj-1\']/div/div/div/div/div/div/div/div/div/div/div/div/div/button/span[6]")).Click();
        driver.FindElement(By.ClassName("aHij0b-aGsRMb")).Click();
        driver.FindElement(By.Id("c13")).Clear();
        driver.FindElement(By.Id("c13")).SendKeys("4");
        driver.FindElement(By.ClassName("MSEcuf")).Click();
        driver.FindElement(By.XPath("//*[@id=\"glue-cookie-notification-bar-1\"]/button")).Click();
        IJavaScriptExecutor js = (IJavaScriptExecutor)driver;
        js.ExecuteScript("var element = document.getElementsByClassName('VfPpkd-gIZMF')[0]; if (element) { element.remove(); }");
        IWebElement element = driver.FindElement(By.CssSelector(".zT2df"));
        element.Click();
        driver.FindElement(By.ClassName("zT2df")).Click();
        driver.FindElement(By.XPath("//label[contains(.,\'Regular\')]")).Click();
        driver.FindElement(By.XPath("//div[11]/div/div/div[2]/div/div/div/div/div/div/div/div")).Click();
        driver.FindElement(By.XPath("//div[2]/div/div/div/div/div/div/div[2]/ul/li")).Click();
        driver.FindElement(By.XPath("//div[2]/div/div/div[2]/div/div/div/div/div")).Click();
        driver.FindElement(By.XPath("//div[2]/div/div/div[2]/div/div/div/div[2]/ul/li")).Click();
        driver.FindElement(By.XPath("//div[2]/div/div/div[3]/div/div/div/div/div")).Click();
        driver.FindElement(By.XPath("//div[3]/div/div/div/div[2]/ul/li[7]")).Click();
        driver.FindElement(By.CssSelector(".U4lDT")).Click();
        driver.FindElement(By.XPath("//div[24]/div/div/div/div/div/div/div")).Click();
        driver.FindElement(By.XPath("//li[contains(.,\'2x375 GB\')]")).Click();
        driver.FindElement(By.XPath("//div[26]/div/div/div/div/div/div/div")).Click();
        driver.FindElement(By.XPath("//li[contains(.,\'Netherlands (europe-west4)\')]")).Click();
        driver.FindElement(By.XPath("//button[@aria-label=\"Add GPUs\"]")).Click();
        driver.FindElement(By.XPath("//div/div/div/div/div/div")).Click();
        driver.FindElement(By.XPath("//div[23]/div/div/div/div/div/div/div")).Click();
        driver.FindElement(By.XPath("//li[contains(.,\'NVIDIA V100\')]")).Click();
        driver.FindElement(By.XPath("//div[@id=\'ow5\']/div/div/div/div/div/div/div/div/div[2]/div[3]/div[24]/div/div/div/div/div/div/div")).Click();
        vars["root"] = driver.CurrentWindowHandle;
        driver.SwitchTo().Window(vars["root"].ToString());
        driver.FindElement(By.XPath("//div[@id=\'ow5\']/div/div/div/div/div/div/div/div/div[2]/div[3]/div[24]/div/div/div/div/div/div[2]/ul/li")).Click();
        js.ExecuteScript("window.scrollTo(0,2364)");
        try
        {
            driver.FindElement(By.ClassName("VfPpkd-aPP78e")).Click();
        }
        catch (ElementClickInterceptedException)
        {
            js.ExecuteScript("var element = document.getElementsByClassName('FOBRw-vQzf8d')[0]; if (element) { element.remove(); }");
            IWebElement option = driver.FindElement(By.XPath("//*[@id=\"ucj-1\"]/div/div/div/div/div/div/div/div[1]/div/div[2]/div[3]/div[24]/div/div[1]/div/div/div/div[1]/div"));
            IJavaScriptExecutor jsExecutor = (IJavaScriptExecutor)driver;
            jsExecutor.ExecuteScript("arguments[0].scrollIntoView(true);", option);
            option.Click();
        }

        finally
        {
            vars["WindowHandles"] = driver.WindowHandles;
            IWebElement button = driver.FindElement(By.CssSelector(".FOBRw-LgbsSe.FOBRw-LgbsSe-OWXEXe-Bz112c-M1Soyc.FOBRw-LgbsSe-OWXEXe-dgl2Hf.FOBRw-LgbsSe-OWXEXe-zcdHbf.VKmq8b.AXySwf"));
            button.Click();
            IWebElement elementToHover = driver.FindElement(By.CssSelector(".RBHQF-ksKsZd"));
            Actions actions2 = new Actions(driver);
            actions2.MoveToElement(elementToHover).Perform();
            IWebElement button1 = driver.FindElement(By.CssSelector(".tltOzc.MExMre.rP2xkc.jl2ntd"));
            button1.Click();
            vars["win3330"] = waitForWindow(2000);
            driver.SwitchTo().Window(vars["win3330"].ToString());
            Assert.That(driver.FindElement(By.XPath("//*[@id=\"yDmH0d\"]/c-wiz[1]/div/div/div/div/div/div[2]/div[2]/div[1]/div/div[2]/div/div[3]/span[2]/span[1]/span[2]")).Text, Is.EqualTo("n1-standard-8, vCPUs: 8, RAM: 30 GB"));
            Assert.That(driver.FindElement(By.XPath("//*[@id=\"yDmH0d\"]/c-wiz[1]/div/div/div/div/div/div[2]/div[2]/div[1]/div/div[2]/div/div[4]/span[2]/span[1]/span[2]")).Text, Is.EqualTo("NVIDIA V100"));
            driver.SwitchTo().Window(vars["win3330"].ToString());
            Assert.That(driver.FindElement(By.XPath("//*[@id=\"yDmH0d\"]/c-wiz[1]/div/div/div/div/div/div[2]/div[2]/div[1]/div/div[2]/div/div[4]/span[3]/span[1]/span[2]")).Text, Is.EqualTo("1"));
            Assert.That(driver.FindElement(By.XPath("//*[@id=\"yDmH0d\"]/c-wiz[1]/div/div/div/div/div/div[2]/div[2]/div[1]/div/div[2]/div/div[5]/span/span[1]/span[2]")).Text, Is.EqualTo("2x375 GB"));
            Assert.That(driver.FindElement(By.XPath("//*[@id=\"yDmH0d\"]/c-wiz[1]/div/div/div/div/div/div[2]/div[2]/div[1]/div/div[2]/div/div[7]/span/span[1]/span[2]")).Text, Is.EqualTo("4"));
            Assert.That(driver.FindElement(By.XPath("//*[@id=\"yDmH0d\"]/c-wiz[1]/div/div/div/div/div/div[2]/div[2]/div[1]/div/div[2]/div/div[8]/span/span[1]/span[2]")).Text, Is.EqualTo("Free: Debian, CentOS, CoreOS, Ubuntu or BYOL (Bring Your Own License)"));
            Assert.That(driver.FindElement(By.XPath("//*[@id=\"yDmH0d\"]/c-wiz[1]/div/div/div/div/div/div[2]/div[2]/div[1]/div/div[2]/div/div[9]/span/span[1]/span[2]")).Text, Is.EqualTo("Regular"));
            Assert.That(driver.FindElement(By.XPath("//*[@id=\"yDmH0d\"]/c-wiz[1]/div/div/div/div/div/div[2]/div[2]/div[1]/div/div[2]/div/div[13]/span/span[1]/span[2]")).Text, Is.EqualTo("true"));
            Assert.That(driver.FindElement(By.XPath("//*[@id=\"yDmH0d\"]/c-wiz[1]/div/div/div/div/div/div[2]/div[2]/div[1]/div/div[2]/div/div[15]/span/span[1]/span[2]")).Text, Is.EqualTo("Netherlands (europe-west4)"));
        }
    }
}
